"""Regression tests for the Nayin (납음오행) module."""
from __future__ import annotations

from saju_engine.nayin import (
    NAYIN_ORDER,
    NAYIN_PAIR_SOURCE,
    NAYIN_PAIR_TABLE,
    nayin_relation,
    nayin_relation_detail,
)


def test_nayin_pair_table_is_complete_30x30():
    """The 30×30 table must contain an entry for every ordered Nayin pair."""
    assert len(NAYIN_ORDER) == 30
    expected_keys = {(a, b) for a in NAYIN_ORDER for b in NAYIN_ORDER}
    assert set(NAYIN_PAIR_TABLE.keys()) == expected_keys
    assert len(NAYIN_PAIR_TABLE) == 30 * 30


def test_nayin_pair_table_same_nayin_is_sangdae():
    """Diagonal entries (same Nayin vs itself) must map to 상대 (+1)."""
    for nayin in NAYIN_ORDER:
        rel, delta = NAYIN_PAIR_TABLE[(nayin, nayin)]
        assert rel == "상대"
        assert delta == 1


def test_nayin_pair_source_tags_are_present():
    """Every table cell must carry a source tag."""
    for key in NAYIN_PAIR_TABLE:
        assert key in NAYIN_PAIR_SOURCE
        assert NAYIN_PAIR_SOURCE[key] in {"element-grammar-fallback", "sourced"}


def test_nayin_relation_detail_returns_source_tag():
    """nayin_relation_detail must expose whether the value is fallback or sourced."""
    rel, delta, tag = nayin_relation_detail("海中金", "爐中火")
    assert isinstance(rel, str)
    assert isinstance(delta, int)
    assert tag == "element-grammar-fallback"


def test_same_nayin_is_mutually_substituting_not_punishment():
    """Same Nayin pair must map to 상대 (+1), not the invented 상형 (-4).

    Regression for engine-audit A9: `knowledge/11-gunghap.md §C` lists the six
    서전구미록 relationships for different Nayins; same-element/Nayin pairs
    reduce to 상대 (相代, mutually substituting). The previous special-case
    returned 상형 (相刑, -4), which was not grounded in the knowledge file.
    """
    rel, delta = nayin_relation("海中金", "海中金")
    assert rel == "상대"
    assert delta == 1


def test_different_nayin_uses_element_grammar():
    """Different Nayins derive the relationship from the underlying elements."""
    # 海中金 (Metal) vs 爐中火 (Fire): Metal is overcome by Fire? No —
    # Fire overcomes Metal in the standard cycle (Fire -> Metal).
    # Metal overcomes Wood; Fire overcomes Metal. So Metal sees Fire as 被克.
    rel, delta = nayin_relation("海中金", "爐中火")
    assert rel in {"상충", "상해", "상합", "상구", "상대", "neutral"}


def test_nayin_relation_is_directed_by_element_cycle():
    """The 서전구미록 element grammar is directional, not symmetric.

    Metal generates Water (생) → 상합 (+3). Water reversed into Metal is the
    reverse-generating (被生) direction → 상구 (+2). Same element stays 상대.
    """
    rel1, delta1 = nayin_relation("海中金", "大溪水")   # Metal generates Water
    rel2, delta2 = nayin_relation("大溪水", "海中金")   # Water is generated by Metal
    assert rel1 == "상합" and delta1 == 3
    assert rel2 == "상구" and delta2 == 2

    # Reversed overcoming direction also differs: Fire overcomes Metal,
    # but Metal being overcome by Fire maps to 상해 (−3), not 상충 (−5).
    rel3, delta3 = nayin_relation("爐中火", "海中金")  # Fire overcomes Metal
    rel4, delta4 = nayin_relation("海中金", "爐中火")  # Metal is overcome by Fire
    assert rel3 == "상충" and delta3 == -5
    assert rel4 == "상해" and delta4 == -3
